package cpo_miniprojet;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author foure
 */
public final class Interface extends javax.swing.JFrame {
    GrilleDeJeu m ;
    public void initialiserPartie() {
        m = new GrilleDeJeu(10,10,10);
        m.initialiserGrille();
    }
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();

        PanneauGrille.setVisible(false);
        initialiserPartie();
        PanneauGrille.setLayout(new java.awt.GridLayout(10, 10)); 
        m.placerBombesAleatoirement(PROPERTIES, PROPERTIES);
        
        for (int i=0; i < 10; i++) { 
            for (int j=0; j < 10; j++ ) { 
                CelluleGraphique c = new CelluleGraphique(m.matriceCellules[i][j], j,i);
                c.addActionListener((java.awt.event.ActionEvent evt) -> {
                    //action a effectuer
                    m.clickSurCellule(c.y , c.x);
                    PanneauGrille.repaint();
                });
                
                PanneauGrille.add(c); // ajout au Jpanel PanneauGrille 
            } 
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Régles = new javax.swing.JButton();
        Jouer = new javax.swing.JButton();
        PanneauGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(600, 600));

        Régles.setBackground(new java.awt.Color(102, 204, 255));
        Régles.setText("Régles");
        Régles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RéglesActionPerformed(evt);
            }
        });

        Jouer.setBackground(new java.awt.Color(255, 255, 153));
        Jouer.setText("Jouer");
        Jouer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Jouer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                JouerCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        Jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JouerActionPerformed(evt);
            }
        });

        PanneauGrille.setBackground(new java.awt.Color(0, 51, 102));
        PanneauGrille.setPreferredSize(new java.awt.Dimension(400, 400));
        PanneauGrille.setLayout(new java.awt.CardLayout(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jouer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Régles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 200, Short.MAX_VALUE)
                    .addComponent(PanneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 200, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Régles, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Jouer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(625, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 195, Short.MAX_VALUE)
                    .addComponent(PanneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 196, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RéglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RéglesActionPerformed
        // TODO add your handling code here:
        String regles = """
                        Règles du Démineur :
                        1. Le but est de découvrir toutes les cases sans mines.
                        2. Les chiffres indiquent le nombre de mines adjacentes.
                        3. Un clic droit place un drapeau pour marquer une mine.
                        4. Si vous cliquez sur une mine, vous perdez.
                        """;
                // Affiche les règles dans une boîte de dialogue
                JOptionPane.showMessageDialog(PanneauGrille, regles, "Règles du Démineur", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RéglesActionPerformed

    private void JouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JouerActionPerformed
        // TODO add your handling code here:
        Jouer.setVisible(false);
        PanneauGrille.setVisible(true);
    }//GEN-LAST:event_JouerActionPerformed

    private void JouerCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JouerCaretPositionChanged

    }//GEN-LAST:event_JouerCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jouer;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton Régles;
    // End of variables declaration//GEN-END:variables

}
